"""Multimodal Assembler for combining text and image content. / 用于组合文本和图片内容的多模态组装器。

This module assembles multimodal MCP responses by: / 本模块通过以下方式组装多模态 MCP 响应：
- Detecting image references in chunk metadata / 检测分块元数据中的图片引用
- Reading image files and encoding to base64 / 读取图片文件并编码为 base64
- Building MCP-compliant ImageContent blocks / 构建符合 MCP 的 ImageContent 块

Design Principles: / 设计原则：
- Lazy loading: Images only loaded when explicitly requested / 延迟加载：仅在明确请求时加载图片
- Error resilience: Missing images don't break text response / 错误韧性：缺失图片不会破坏文本响应
- Format detection: Automatic MIME type inference from file content / 格式检测：根据文件内容自动推断 MIME 类型
"""

from __future__ import annotations

import base64
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from mcp import types

from src.core.types import RetrievalResult


logger = logging.getLogger(__name__)


# Supported image formats and their MIME types / 支持的图片格式及其 MIME 类型
MIME_TYPE_MAP: Dict[str, str] = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".bmp": "image/bmp",
    ".svg": "image/svg+xml",
}

# Magic bytes for format detection (fallback when extension unreliable) / 用于格式检测的魔数（扩展名不可靠时的回退）
MAGIC_BYTES: Dict[bytes, str] = {
    b"\x89PNG\r\n\x1a\n": "image/png",
    b"\xff\xd8\xff": "image/jpeg",
    b"GIF87a": "image/gif",
    b"GIF89a": "image/gif",
    b"RIFF": "image/webp",  # WebP starts with RIFF / WebP 以 RIFF 开头
    b"BM": "image/bmp",
}

# Image placeholder pattern in text: [IMAGE: image_id] / 文本中的图片占位符模式：[IMAGE: image_id]
IMAGE_PLACEHOLDER_PATTERN = re.compile(r"\[IMAGE:\s*([^\]]+)\]")


@dataclass
class ImageReference:
    """Reference to an image within a chunk. / 分块内的图片引用。
    
    Attributes: / 属性：
        image_id: Unique identifier for the image / image_id：图片唯一标识
        file_path: Filesystem path to the image file / file_path：图片文件的文件系统路径
        page: Optional page number in source document / page：源文档中的可选页码
        text_offset: Character offset of placeholder in chunk text / text_offset：占位符在分块文本中的字符偏移
        text_length: Length of the placeholder string / text_length：占位符字符串长度
        caption: Optional caption generated by ImageCaptioner / caption：ImageCaptioner 生成的可选图片描述
    """
    image_id: str
    file_path: Optional[str] = None
    page: Optional[int] = None
    text_offset: Optional[int] = None
    text_length: Optional[int] = None
    caption: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary. / 转换为字典。"""
        return {
            "image_id": self.image_id,
            "file_path": self.file_path,
            "page": self.page,
            "text_offset": self.text_offset,
            "text_length": self.text_length,
            "caption": self.caption,
        }


@dataclass
class ImageContent:
    """Loaded image content ready for MCP response. / 已加载且可用于 MCP 响应的图片内容。
    
    Attributes: / 属性：
        image_id: Unique identifier for the image / image_id：图片唯一标识
        data: Base64-encoded image data / data：Base64 编码的图片数据
        mime_type: MIME type (e.g., "image/png") / mime_type：MIME 类型（例如 "image/png"）
        caption: Optional caption for the image / caption：图片的可选描述
    """
    image_id: str
    data: str  # base64 encoded / base64 编码
    mime_type: str
    caption: Optional[str] = None
    
    def to_mcp_content(self) -> types.ImageContent:
        """Convert to MCP ImageContent block. / 转换为 MCP ImageContent 块。
        
        Returns: / 返回：
            MCP ImageContent object for protocol response. / 用于协议响应的 MCP ImageContent 对象。
        """
        return types.ImageContent(
            type="image",
            data=self.data,
            mimeType=self.mime_type,
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary. / 转换为字典。"""
        return {
            "image_id": self.image_id,
            "data": self.data,
            "mime_type": self.mime_type,
            "caption": self.caption,
        }


class MultimodalAssembler:
    """Assembles multimodal content from retrieval results. / 从检索结果组装多模态内容。
    
    This class extracts image references from chunk metadata, / 该类从分块元数据中提取图片引用，
    loads image files, and builds MCP-compliant content blocks / 加载图片文件，并构建符合 MCP 的内容块，
    combining text and images. / 组合文本和图片。
    
    Example: / 示例：
        >>> assembler = MultimodalAssembler()
        >>> results = [RetrievalResult(chunk_id="doc1_001", ...)]
        >>> content_blocks = assembler.assemble(results)
        >>> # Returns list of TextContent and ImageContent blocks / 返回 TextContent 和 ImageContent 块列表
    
    Args: / 参数：
        image_storage: Optional ImageStorage instance for path lookup. / image_storage：用于路径查找的可选 ImageStorage 实例。
            If None, uses file paths directly from metadata. / 如果为 None，则直接使用元数据中的文件路径。
        max_images_per_result: Maximum images to include per result (default: 5). / max_images_per_result：每条结果最多包含的图片数量（默认值：5）。
        include_captions: Whether to include image captions as text (default: True). / include_captions：是否将图片描述作为文本包含（默认值：True）。
    """
    
    def __init__(
        self,
        image_storage: Optional[Any] = None,
        max_images_per_result: int = 5,
        include_captions: bool = True,
    ) -> None:
        """Initialize MultimodalAssembler. / 初始化 MultimodalAssembler。
        
        Args: / 参数：
            image_storage: Optional ImageStorage for resolving image paths. / image_storage：用于解析图片路径的可选 ImageStorage。
            max_images_per_result: Max images to include per retrieval result. / max_images_per_result：每条检索结果最多包含的图片数量。
            include_captions: Whether to add caption text blocks. / include_captions：是否添加描述文本块。
        """
        self._image_storage = image_storage
        self.max_images_per_result = max_images_per_result
        self.include_captions = include_captions
    
    def extract_image_refs(
        self,
        result: RetrievalResult,
    ) -> List[ImageReference]:
        """Extract image references from a retrieval result. / 从检索结果中提取图片引用。
        
        Looks for image references in: / 在以下位置查找图片引用：
        1. metadata.images list (structured image info) / 1. metadata.images 列表（结构化图片信息）
        2. [IMAGE: id] placeholders in text (fallback) / 2. 文本中的 [IMAGE: id] 占位符（回退）
        
        Args: / 参数：
            result: RetrievalResult containing chunk data. / result：包含分块数据的 RetrievalResult。
            
        Returns: / 返回：
            List of ImageReference objects found in the result. / 在结果中找到的 ImageReference 对象列表。
        """
        refs: List[ImageReference] = []
        metadata = result.metadata or {}
        
        # Primary source: structured images list in metadata / 主要来源：元数据中的结构化 images 列表
        images_list = metadata.get("images", [])
        if isinstance(images_list, list):
            for img_info in images_list[:self.max_images_per_result]:
                if isinstance(img_info, dict) and "id" in img_info:
                    ref = ImageReference(
                        image_id=img_info["id"],
                        file_path=img_info.get("path"),
                        page=img_info.get("page"),
                        text_offset=img_info.get("text_offset"),
                        text_length=img_info.get("text_length"),
                    )
                    refs.append(ref)
        
        # Add captions if available / 如果可用则添加图片描述
        captions = metadata.get("image_captions", {})
        if isinstance(captions, dict):
            for ref in refs:
                if ref.image_id in captions:
                    ref.caption = captions[ref.image_id]
        
        # Fallback: parse placeholders from text if no structured refs / 回退：如果没有结构化引用，则从文本中解析占位符
        if not refs and result.text:
            placeholders = IMAGE_PLACEHOLDER_PATTERN.findall(result.text)
            for image_id in placeholders[:self.max_images_per_result]:
                image_id = image_id.strip()
                ref = ImageReference(
                    image_id=image_id,
                    caption=captions.get(image_id) if isinstance(captions, dict) else None,
                )
                refs.append(ref)
        
        return refs
    
    def resolve_image_path(
        self,
        ref: ImageReference,
        collection: Optional[str] = None,
    ) -> Optional[str]:
        """Resolve the filesystem path for an image reference. / 解析图片引用对应的文件系统路径。
        
        Args: / 参数：
            ref: ImageReference to resolve. / ref：要解析的 ImageReference。
            collection: Optional collection name for path construction. / collection：用于构造路径的可选集合名称。
            
        Returns: / 返回：
            Absolute file path if found, None otherwise. / 如果找到则返回绝对文件路径，否则返回 None。
        """
        # Use explicit path if available / 如果有显式路径则使用
        if ref.file_path:
            path = Path(ref.file_path)
            if path.exists():
                return str(path.resolve())
        
        # Try ImageStorage lookup / 尝试通过 ImageStorage 查找
        if self._image_storage is not None:
            try:
                path = self._image_storage.get_image_path(ref.image_id)
                if path and Path(path).exists():
                    return path
            except Exception as e:
                logger.warning(f"ImageStorage lookup failed for {ref.image_id}: {e}")
        
        # Convention-based path: data/images/{collection}/{image_id}.png / 基于约定的路径：data/images/{collection}/{image_id}.png
        if collection:
            from src.core.settings import resolve_path
            for ext in [".png", ".jpg", ".jpeg", ".webp"]:
                candidate = resolve_path(f"data/images/{collection}/{ref.image_id}{ext}")
                if candidate.exists():
                    return str(candidate.resolve())
        
        return None
    
    def load_image(
        self,
        file_path: str,
    ) -> Optional[ImageContent]:
        """Load and encode an image file. / 加载并编码图片文件。
        
        Args: / 参数：
            file_path: Path to the image file. / file_path：图片文件路径。
            
        Returns: / 返回：
            ImageContent with base64 data and MIME type, or None on failure. / 包含 base64 数据和 MIME 类型的 ImageContent，失败时返回 None。
        """
        try:
            path = Path(file_path)
            if not path.exists():
                logger.warning(f"Image file not found: {file_path}")
                return None
            
            # Read file content / 读取文件内容
            data = path.read_bytes()
            if not data:
                logger.warning(f"Empty image file: {file_path}")
                return None
            
            # Detect MIME type / 检测 MIME 类型
            mime_type = self._detect_mime_type(path, data)
            
            # Encode to base64 / 编码为 base64
            base64_data = base64.b64encode(data).decode("utf-8")
            
            return ImageContent(
                image_id=path.stem,
                data=base64_data,
                mime_type=mime_type,
            )
            
        except Exception as e:
            logger.error(f"Failed to load image {file_path}: {e}")
            return None
    
    def _detect_mime_type(
        self,
        path: Path,
        data: bytes,
    ) -> str:
        """Detect MIME type from file extension or magic bytes. / 根据文件扩展名或魔数检测 MIME 类型。
        
        Args: / 参数：
            path: File path for extension detection. / path：用于扩展名检测的文件路径。
            data: File content for magic byte detection. / data：用于魔数检测的文件内容。
            
        Returns: / 返回：
            MIME type string (defaults to "image/png" if unknown). / MIME 类型字符串（未知时默认 "image/png"）。
        """
        # Try extension first / 先尝试扩展名
        suffix = path.suffix.lower()
        if suffix in MIME_TYPE_MAP:
            return MIME_TYPE_MAP[suffix]
        
        # Fallback to magic bytes / 回退到魔数检测
        for magic, mime_type in MAGIC_BYTES.items():
            if data.startswith(magic):
                return mime_type
        
        # Default to PNG / 默认使用 PNG
        logger.debug(f"Unknown image format for {path}, defaulting to image/png")
        return "image/png"
    
    def assemble_for_result(
        self,
        result: RetrievalResult,
        collection: Optional[str] = None,
    ) -> List[Union[types.TextContent, types.ImageContent]]:
        """Assemble multimodal content blocks for a single result. / 为单条结果组装多模态内容块。
        
        Args: / 参数：
            result: RetrievalResult to process. / result：要处理的 RetrievalResult。
            collection: Optional collection name for path resolution. / collection：用于路径解析的可选集合名称。
            
        Returns: / 返回：
            List of MCP content blocks (TextContent and ImageContent). / MCP 内容块列表（TextContent 和 ImageContent）。
        """
        blocks: List[Union[types.TextContent, types.ImageContent]] = []
        
        # Extract image references / 提取图片引用
        refs = self.extract_image_refs(result)
        
        # Load and add images / 加载并添加图片
        for ref in refs:
            # Resolve path / 解析路径
            file_path = self.resolve_image_path(ref, collection)
            if not file_path:
                logger.debug(f"Could not resolve path for image: {ref.image_id}")
                continue
            
            # Load image / 加载图片
            image_content = self.load_image(file_path)
            if image_content is None:
                continue
            
            # Update with reference info / 使用引用信息更新
            image_content.image_id = ref.image_id
            image_content.caption = ref.caption
            
            # Add image block / 添加图片块
            blocks.append(image_content.to_mcp_content())
            
            # Add caption as text if enabled / 如果启用，则将图片描述作为文本添加
            if self.include_captions and ref.caption:
                caption_text = f"**Image Caption ({ref.image_id}):** {ref.caption}"
                blocks.append(types.TextContent(type="text", text=caption_text))
        
        return blocks
    
    def assemble(
        self,
        results: List[RetrievalResult],
        collection: Optional[str] = None,
    ) -> List[Union[types.TextContent, types.ImageContent]]:
        """Assemble multimodal content blocks for multiple results. / 为多条结果组装多模态内容块。
        
        Args: / 参数：
            results: List of RetrievalResult to process. / results：要处理的 RetrievalResult 列表。
            collection: Optional collection name for path resolution. / collection：用于路径解析的可选集合名称。
            
        Returns: / 返回：
            List of all MCP content blocks from all results. / 所有结果中的全部 MCP 内容块列表。
        """
        all_blocks: List[Union[types.TextContent, types.ImageContent]] = []
        seen_image_ids: set = set()
        
        for result in results:
            blocks = self.assemble_for_result(result, collection)
            
            # Deduplicate images across results / 对跨结果图片去重
            for block in blocks:
                if isinstance(block, types.ImageContent):
                    # Check if we've seen this image / 检查是否已见过该图片
                    # ImageContent doesn't have image_id, so we hash the data / ImageContent 没有 image_id，因此对 data 取哈希
                    data_hash = hash(block.data[:100])  # Use prefix for efficiency / 使用前缀提高效率
                    if data_hash in seen_image_ids:
                        continue
                    seen_image_ids.add(data_hash)
                
                all_blocks.append(block)
        
        return all_blocks
    
    def has_images(self, result: RetrievalResult) -> bool:
        """Check if a result contains image references. / 检查结果是否包含图片引用。
        
        Args: / 参数：
            result: RetrievalResult to check. / result：要检查的 RetrievalResult。
            
        Returns: / 返回：
            True if result has image references, False otherwise. / 如果结果有图片引用则返回 True，否则返回 False。
        """
        refs = self.extract_image_refs(result)
        return len(refs) > 0
    
    def count_images(self, results: List[RetrievalResult]) -> int:
        """Count total images across all results. / 统计所有结果中的图片总数。
        
        Args: / 参数：
            results: List of RetrievalResult to count. / results：要统计的 RetrievalResult 列表。
            
        Returns: / 返回：
            Total number of image references found. / 找到的图片引用总数。
        """
        total = 0
        for result in results:
            refs = self.extract_image_refs(result)
            total += len(refs)
        return total
